server:
  port: 6600
#server.context-path=/gapi

spring:
  application:
    name: gateway-api
  session:
    store-type: redis
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    jpa:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: 172.31.50.56:9092
    consumer:
      group-id: default-group
    template:
      default-topic: test
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
  redis:
    host: 172.31.50.183
    password: ENC(SXuWnz79A4slMYdgrHNIwMLzSEameA/o)
    port: 6379
    database: 0
    timeout: 1000000
    maxTotal: 500
    pool:
      max-idle: 20
      min-idle: 20
      max-active: 200
      max-wait: 1000
  jackson:
    serialization:
      indent_output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 10MB # 设置单个文件的最大长度

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.48.134:7000/eureka/,http://172.31.48.120:7000/eureka/

#ribbon超时设置
#ReadTimeout 设置路由转发请求的时候，创建请求连接的超时时间
#ConnectTimeout 用来设置路由转发请求的超时时间
ribbon:
  ReadTimeout: 11000
  ConnectTimeout: 11000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

# test
updating-api:
  ribbon:
    ReadTimeout: 21000
    ConnectTimeout: 21000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
ucenter-api:
  ribbon:
    ReadTimeout: 21000
    ConnectTimeout: 21000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-exchange-api:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-exchange-vip-api:
  ribbon:
    ReadTimeout: 16000
    ConnectTimeout: 16000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
bitrade-market:
  ribbon:
    ReadTimeout: 6000
    ConnectTimeout: 6000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-otc:
  ribbon:
    ReadTimeout: 21000
    ConnectTimeout: 21000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true

service-notice:
  ribbon:
    ReadTimeout: 21000
    ConnectTimeout: 21000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true

service-chat:
  ribbon:
    ReadTimeout: 6000
    ConnectTimeout: 6000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-pay-api:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
bitrade-open-api:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
guess-api:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-lock:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true
service-lock-hqb:
  ribbon:
    ReadTimeout: 11000
    ConnectTimeout: 11000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    eureka:
      enabled: true

#hystrix超时配置
#设置API网关中路由转发请求的HystrixCommand执行超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    updating-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    ucenter-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    service-exchange-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    service-exchange-vip-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
    bitrade-market:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    service-otc:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    service-notice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    service-chat:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    service-pay-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    bitrade-open-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    guess-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    service-lock:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    service-lock-hqb:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

### zuul.routes 网管api配置
## zuul.ratelimit 限流配置
#限流类型：url、origin、user
zuul:
  routes:
    updating:
      serviceId: updating-api
      path: /updating/**
      stripPrefix: false
      customSensitiveHeaders: true
    uc:
      serviceId: ucenter-api
      path: /uc/**
      stripPrefix: false
      customSensitiveHeaders: true
    exchange:
      serviceId: service-exchange-api
      path: /exchange/**
      stripPrefix: false
      customSensitiveHeaders: true
    exchange-vpi:
      serviceId: service-exchange-vip-api
      path: /exchange-vip/**
      stripPrefix: false
      customSensitiveHeaders: true
    market:
      serviceId: bitrade-market
      path: /market/**
      stripPrefix: false
      customSensitiveHeaders: true
    otc:
      serviceId: service-otc
      path: /otc/**
      stripPrefix: false
      customSensitiveHeaders: true
    chat:
      serviceId: service-chat
      path: /chat/**
      stripPrefix: false
      customSensitiveHeaders: true
    api:
      serviceId: bitrade-open-api
      path: /api/**
      stripPrefix: false
      customSensitiveHeaders: true
    extrade:
      serviceId: service-exchange-trade
      path: /extrade/**
      stripPrefix: false
      customSensitiveHeaders: true
    pay:
      serviceId: service-pay-api
      path: /pay/**
      stripPrefix: false
      customSensitiveHeaders: true
    guess-api:
      serviceId: guess-api
      path: /guess-api/**
      stripPrefix: false
      customSensitiveHeaders: true
    lock-api:
      serviceId: service-lock
      path: /lock-api/**
      stripPrefix: false
      customSensitiveHeaders: true
    lock-hqb-api:
      serviceId: service-lock-hqb
      path: /lock-hqb-api/**
      stripPrefix: false
      customSensitiveHeaders: true
    notice:
      serviceId: service-notice
      path: /notice/**
      stripPrefix: false
      customSensitiveHeaders: true
  ratelimit:
    enabled: true
    repository: REDIS
    policies:
      updating:
        limit: 240
        refresh-interval: 60
        type: url,origin
      uc:
        limit: 240
        refresh-interval: 60
        type: url
      exchange:
        limit: 600
        refresh-interval: 60
        type: url
      exchange-vip:
        limit: 120000
        refresh-interval: 60
        type: url
      market:
        limit: 240
        refresh-interval: 60
        type: url
      otc:
        limit: 180
        refresh-interval: 60
        type: url
      chat:
        limit: 180
        refresh-interval: 60
        type: url
      api:
        limit: 1000
        refresh-interval: 60
        type: url
      extrade:
        limit: 120
        refresh-interval: 60
        type: url
      pay:
        limit: 60000
        refresh-interval: 60
        type: url
      guess-api:
        limit: 120
        refresh-interval: 60
        type: url
      lock-api:
        limit: 60
        refresh-interval: 60
        type: url
      lock-hqb-api:
        limit: 60
        refresh-interval: 60
        type: url
      notice:
        limit: 600
        refresh-interval: 60
        type: url

###mybatis读写分离配置
#mybatis.mapperScanPackage=com.spark.bitrade.mapper.dao
mybatis:
  mapperLocations: classpath:/com/spark/bitrade/mapper/dao/*.xml
  typeAliasesPackage: com.spark.bitrade.mapper.dao
  configLocation: classpath:/mybatis-config.xml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

##读写库分离配置
#mysql.datasource.write 写数据库配置
mysql:
  datasource:
    write:
      url: jdbc:mysql://silktrader.cozqhg64ejiq.ap-northeast-1.rds.amazonaws.com:3306/silktrader?characterEncoding=utf-8
      username: dk-gateway-api
      password: ENC(ZpXin2uUdU8dbEswJbyXp2DCAN3a2FdPmHDHiqWARA0=)
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 0
      minIdle: 0
      maxActive: 1
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 50
      removeAbandoned: true
      filters: stat
    read01:
      url: jdbc:mysql://silktrader-readonly.cozqhg64ejiq.ap-northeast-1.rds.amazonaws.com:3306/silktrader?characterEncoding=utf-8
      username : dk-gateway-api
      password : ENC(ZpXin2uUdU8dbEswJbyXp2DCAN3a2FdPmHDHiqWARA0=)
      driver-class-name : com.mysql.jdbc.Driver
      initialSize : 0
      minIdle : 0
      maxActive : 1
      maxWait : 60000
      timeBetweenEvictionRunsMillis : 60000
      minEvictableIdleTimeMillis : 300000
      validationQuery : select 'x'
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 50
      removeAbandoned : true
      filters : stat
    read02:
      url: jdbc:mysql://silktrader-readonly.cozqhg64ejiq.ap-northeast-1.rds.amazonaws.com:3306/silktrader?characterEncoding=utf-8
      username : dk-gateway-api
      password : ENC(ZpXin2uUdU8dbEswJbyXp2DCAN3a2FdPmHDHiqWARA0=)
      driver-class-name : com.mysql.jdbc.Driver
      initialSize : 0
      minIdle : 0
      maxActive : 1
      maxWait : 60000
      timeBetweenEvictionRunsMillis : 60000
      minEvictableIdleTimeMillis : 300000
      validationQuery : select 'x'
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 50
      removeAbandoned : true
      filters : stat

#系统测试账号
user:
  tester:
    whitelist:
      - 71639 #杨从洪
      - 103228 #公司测试账号17388227128
      - 100718 #公司测试账号17602373876
      - 70653 #谌祖财
      - 74365 #高部
      - 102839 #张彦君
      - 283596 #廖玉珍
      - 69877 #林丹
      - 100036 #詹朋
      - 105408 #黄佳杰
      - 155414 #内部机器人摆盘
      - 376619 #新机器人
      - 376622 #新机器人
      - 376623 #新机器人
      - 69865 #超盘手
      - 69900 #超盘手
